Rebuild bin/dotify

diff --git a/bin/dotify b/bin/dotify
--- a/bin/dotify
+++ b/bin/dotify
@@ -121,6 +121,11 @@ compile-dotfile() {
   local dotfile="$1"
   if [ -z "$dotfile" ]; then dotfile="$DOTFILE"; fi
 
+  if [ ! -f "$dotfile" ]; then
+    echo "ERROR: \"$dotfile\" does not exist." >&2
+    return 1
+  fi
+
   local output=""
   local line=""
   while IFS= read line; do
@@ -263,7 +268,7 @@ dotify-compile() {
   locate-dotfile
   if [ "$?" != "0" ]; then return 1; fi
 
-  compile-dotfile
+  compile-dotfile "$DOTFILE"
   return $?
 }
 
